// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/iniyusril/template/app"
	"github.com/iniyusril/template/controller"
	"github.com/iniyusril/template/repository"
	"github.com/iniyusril/template/service"
	"github.com/labstack/echo/v4"
)

// Injectors from inject.go:

func InitializedServer() *echo.Echo {
	categoryRepository := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := validator.New()
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository, db, validate)
	userController := controller.NewUserController(userService)
	echoEcho := app.NewRouter(categoryController, userController)
	return echoEcho
}

// inject.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)
